#!/bin/bash
set -e -u

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

bundle install
npm install

if [ $# -ge 1 ] && [ "$1" = "--dev" ]; then
    npx nf start --procfile Procfile.dev
else
    npx nf start
fi
