name: Clean Up
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Read Node version
      id: node_version
      run: cat .node_version

    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.node_version.outputs.value }}

    - name: Install
      run: npm install

    - name: Run fix
      run: npm run lint:fix

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply lint fixes 🤖
